### ISSUE TITLE
Carve deleted files

### ISSUE THREAD

**Issue by wywin** [TranscranialOrchestra/BitCollector#18]
Miscreants delete incriminating files. Unless they overwrite them, we can dig them back up! Let's do that!

**Comment by wywin** [comment]
I want to add the module label to this, but apparently I don't have the correct permissions to do so...

**Comment by albinohat** [comment]
Unfortunately, GitHub limits access to labels and everything else juicy to those with write permissions. 

I have created a new repository in the org called BitCollector-Issues. We will use the issue tracker there since everyone can have write access. I will populate that issue tracker tonight.

Thank you very much for pointing this out!
